### ISSUE TITLE
Check if icon exists

### ISSUE THREAD

**Issue by VictorPietro** [DATechnologies/react-fa-icon-picker#9]
Hi! Thanks for this. I am building this website in which an user can select an icon and send it to backend, where it will be saved.

For validation purposes, I am trying to check (on the backend) if the icon name is valid - i.e., if it's one of the icons available within the react-fa-icon-picker.

Has anyone done anything similar to this?

**Comment by ghost** [comment]
It's a bit of a manual process, but the available icons are listed in https://github.com/DATechnologies/react-fa-icon-picker/blob/master/src/iconList.ts, so a copy of that on the backend serving as a lookup would achieve what you want I think?

**Comment by VictorPietro** [comment]
Hi @Chuckatron, fantastic, thank you!! That will definitely work out for what I need.
